# Optimized CI/CD Pipeline - Quality Gates Only
name: Quality Gates

on:
  push:
    branches: ["feature/**"]  # Only feature branches
  pull_request:
    branches: [main, develop]   # PRs to main/develop

jobs:
  quality-check:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run tests
        run: npm run test:unit
      - name: Security scan
        run: npm audit --audit-level=high
      - name: Validate configuration
        run: |
          test -f vercel.json
          python3 -m json.tool vercel.json > /dev/null

  build-validation:
    name: Build Validation
    runs-on: ubuntu-latest
    needs: quality-check
    steps:
      - uses: actions/checkout@v4
      - name: Validate file structure
        run: |
          # Only essential file checks
          test -f pages/home.html
          test -f pages/tickets.html
          test -f vercel.json
      - name: Test static serving
        run: |
          python3 -m http.server 8000 &
          SERVER_PID=$!
          sleep 3
          curl -f http://localhost:8000/pages/home.html
          kill $SERVER_PID