-- Migration 002b: QR code system for tickets (IDEMPOTENT)
-- Note: QR code fields and validations table are now defined in 018_tickets_table.sql
-- This migration is now a no-op as all structures are defined in the tickets table schema