-- Migration: Add registration tracking to tickets table (IDEMPOTENT)
-- Purpose: Registration tracking fields and indexes are now defined in 018_tickets_table.sql
-- Requirements: REQ-DB-001
-- Created: 2025-01-23
-- This migration is now a no-op as all structures are defined in the tickets table schema

-- Down Migration (Rollback)
-- DROP INDEX IF EXISTS idx_tickets_deadline;
-- DROP INDEX IF EXISTS idx_tickets_registration_status;
-- ALTER TABLE tickets DROP COLUMN registration_deadline;
-- ALTER TABLE tickets DROP COLUMN registered_at;
-- ALTER TABLE tickets DROP COLUMN registration_status;