-- Migration: Add registration tracking fields to transactions table (IDEMPOTENT)
-- Purpose: Track registration tokens and completion status at transaction level
-- Requirements: REQ-DB-001, REQ-SEC-001
-- Created: 2025-01-23
-- Note: These columns and constraints are now defined in core tables (001_core_tables.sql)
-- This migration is now a no-op as all structures are defined in the core schema

-- Down Migration (Rollback)
-- DROP TRIGGER IF EXISTS trg_transactions_token_upd_chk;
-- DROP TRIGGER IF EXISTS trg_transactions_token_ins_chk;
-- DROP INDEX IF EXISTS idx_transactions_registration_token;
-- ALTER TABLE transactions DROP COLUMN all_tickets_registered;
-- ALTER TABLE transactions DROP COLUMN registration_completed_at;
-- ALTER TABLE transactions DROP COLUMN registration_initiated_at;
-- ALTER TABLE transactions DROP COLUMN registration_token_expires;
-- ALTER TABLE transactions DROP COLUMN registration_token;