-- Migration: 047 - Reduce Scan Limit for Future Tickets
-- Purpose: Change default max_scan_count from 10 to 3 scans
-- Dependencies: 005_tickets.sql
--
-- RATIONALE:
-- The event uses wristband-based access control where:
-- 1. First scan → Attendee receives physical wristband
-- 2. Wristband → Provides all subsequent venue access (no more scans needed)
-- 3. Additional scans (2-3) → Error recovery only (QR read failures, network issues)
--
-- The previous limit of 10 scans was too generous and could enable ticket sharing abuse.
-- New limit of 3 scans provides adequate error recovery while preventing misuse.
--
-- STRATEGY:
-- Update the default value in migration 005_tickets.sql (already completed)
-- Existing tickets retain their current max_scan_count values (unchanged)
-- New tickets created after this change will use max_scan_count = 3
--
-- CHANGES MADE:
-- 1. migrations/005_tickets.sql:42 - Changed DEFAULT 10 to DEFAULT 3
-- 2. api/tickets/[ticketId].js:116,180,183 - Updated fallback from || 10 to || 3
-- 3. api/registration/index.js:135-137 - Added scan tracking fields to API response
--
-- IMPACT:
-- - Existing tickets: Keep current max_scan_count (typically 10)
-- - New tickets: Will use max_scan_count = 3
-- - No data migration required
-- - No breaking changes to API contracts
--
-- This migration file serves as documentation of the policy change.
-- No SQL statements needed as the change was made directly to the base schema.
