name: Test Infrastructure Complexity Check

on:
  pull_request:
    paths:
      - 'tests/**'
      - 'scripts/test-*.js'
      - 'scripts/**test**.js'

jobs:
  complexity-check:
    runs-on: ubuntu-latest
    name: Prevent Test Infrastructure Bloat
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Check Test Infrastructure Complexity
        run: |
          echo "🔍 Analyzing test infrastructure complexity..."
          
          # Count total lines in streamlined test framework
          TOTAL_TEST_LINES=$(find tests -name "*.js" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo 0)
          
          # Count test files
          TEST_FILE_COUNT=$(find tests -name "*.js" | wc -l || echo 0)
          
          # Count utility files (should be minimal)
          UTIL_FILE_COUNT=$(find tests \( -name "helpers.js" -o -name "setup.js" \) -type f 2>/dev/null | wc -l || echo 0)
          
          echo "📊 Current Test Infrastructure Metrics:"
          echo "  Total test lines: $TOTAL_TEST_LINES"
          echo "  Test file count: $TEST_FILE_COUNT" 
          echo "  Utility file count: $UTIL_FILE_COUNT"
          
          # Check total lines threshold - streamlined target is 500 lines max
          if [ "$TOTAL_TEST_LINES" -gt 500 ]; then
            echo "❌ COMPLEXITY FAILURE: Total test lines ($TOTAL_TEST_LINES) exceeds 500 line threshold"
            echo "   The streamlined test approach should stay under 500 lines total. Consider:"
            echo "   • Removing unnecessary test abstractions"
            echo "   • Simplifying test helper functions"
            echo "   • Using direct assertions instead of complex helpers"
            echo "   • Focus only on critical business flows"
            exit 1
          fi
          
          # Check for oversized test files
          echo "🔍 Checking individual test file sizes..."
          OVERSIZED_FILES=""
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              LINE_COUNT=$(wc -l < "$file")
              if [ "$LINE_COUNT" -gt 200 ]; then
                echo "⚠️  Large test file: $file ($LINE_COUNT lines)"
                OVERSIZED_FILES="$OVERSIZED_FILES\n  $file ($LINE_COUNT lines)"
              fi
            fi
          done < <(find tests -name "*.test.js" -type f 2>/dev/null || true)
          
          # Check for oversized utility files
          echo "🔍 Checking utility file sizes..."
          OVERSIZED_UTILS=""
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              LINE_COUNT=$(wc -l < "$file")
              if [ "$LINE_COUNT" -gt 150 ]; then
                echo "⚠️  Large utility file: $file ($LINE_COUNT lines)"
                OVERSIZED_UTILS="$OVERSIZED_UTILS\n  $file ($LINE_COUNT lines)"
              fi
            fi
          done < <(find tests \( -name "helpers.js" -o -name "setup.js" \) -type f 2>/dev/null || true)
          
          # Report oversized files as warnings, not failures
          if [ -n "$OVERSIZED_FILES" ]; then
            echo "⚠️  WARNING: Large test files detected (>200 lines):"
            echo -e "$OVERSIZED_FILES"
            echo "   Consider breaking these into smaller, focused tests"
          fi
          
          if [ -n "$OVERSIZED_UTILS" ]; then
            echo "⚠️  WARNING: Large utility files detected (>150 lines):"
            echo -e "$OVERSIZED_UTILS" 
            echo "   Consider if these utilities add necessary value or create complexity"
          fi
          
          # Success message
          echo "✅ Test infrastructure complexity within acceptable limits"
          echo "   Keep tests simple and focused!"

      - name: Generate Complexity Report
        run: |
          echo "📋 Test Infrastructure Complexity Report" > complexity-report.md
          echo "Generated: $(date)" >> complexity-report.md
          echo "" >> complexity-report.md
          
          # Metrics for streamlined tests
          TOTAL_LINES=$(find tests -name "*.js" -exec wc -l {} + 2>/dev/null | tail -1 | awk '{print $1}' || echo 0)
          FILE_COUNT=$(find tests -name "*.js" | wc -l || echo 0)
          UTIL_COUNT=$(find tests -name "helpers.js" -o -name "setup.js" 2>/dev/null | wc -l || echo 0)
          
          echo "## Current Metrics" >> complexity-report.md
          echo "- **Total Lines**: $TOTAL_LINES / 500 threshold (streamlined)" >> complexity-report.md
          echo "- **Test Files**: $FILE_COUNT" >> complexity-report.md  
          echo "- **Utility Files**: $UTIL_COUNT" >> complexity-report.md
          echo "" >> complexity-report.md
          
          # Top 5 largest files
          echo "## Largest Test Files" >> complexity-report.md
          find tests -name "*.js" -exec wc -l {} + 2>/dev/null | grep -vE '\\stotal$' | sort -nr | head -5 | while read line file; do
            echo "- $file: $line lines" >> complexity-report.md
          done
          
          # Prevention guidance
          echo "" >> complexity-report.md
          echo "## Streamlined Test Guidelines" >> complexity-report.md
          echo "- **Total test suite**: Stay under 500 lines" >> complexity-report.md
          echo "- **Individual test files**: Under 200 lines each" >> complexity-report.md
          echo "- **Helper files**: Under 100 lines each" >> complexity-report.md
          echo "- **Focus**: Test critical business flows only" >> complexity-report.md
          echo "- **Approach**: Direct API calls, no complex mocking" >> complexity-report.md
          echo "- **Simplicity**: Any developer should understand tests immediately" >> complexity-report.md
        
      - name: Upload Complexity Report
        uses: actions/upload-artifact@v4
        with:
          name: test-complexity-report
          path: complexity-report.md