name: "📸 Monthly Database Snapshot"

on:
  schedule:
    # 1st of every month at 3 AM UTC
    - cron: '0 3 1 * *'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (show what would happen without making changes)'
        required: false
        default: false
        type: boolean
  # TEMPORARY: Testing workflow on fix/turso-backups branch
  # TODO: Remove these triggers before merging to main
  push:
    branches:
      - fix/turso-backups
  pull_request:
    branches:
      - fix/turso-backups

permissions:
  contents: read

jobs:
  snapshot:
    name: "📸 Create Monthly Snapshots"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "🔧 Install Turso CLI"
        run: |
          echo "🔧 Installing Turso CLI..."
          curl -sSfL https://get.tur.so/install.sh | bash

          # Verify installation
          if [ ! -f "$HOME/.turso/turso" ]; then
            echo "❌ Turso CLI installation failed - binary not found"
            exit 1
          fi

          echo "✅ Turso CLI installed: $(ls -lh $HOME/.turso/turso)"

          # Add to PATH for subsequent steps (correct directory)
          echo "$HOME/.turso" >> $GITHUB_PATH

      - name: "🔐 Verify Turso API Token"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
        run: |
          echo "🔐 Verifying Turso API token..."

          # Check if token is set
          if [ -z "$TURSO_API_TOKEN" ]; then
            echo "❌ TURSO_API_TOKEN secret is not set"
            echo ""
            echo "📝 Fix: Go to GitHub Settings → Secrets → Actions → New secret"
            echo "   Name: TURSO_API_TOKEN"
            echo "   Value: Run 'turso auth token' to get your platform API token"
            echo ""
            echo "⚠️  Note: TURSO_API_TOKEN (platform token) is different from"
            echo "   TURSO_AUTH_TOKEN (database connection token)"
            exit 1
          fi

          # Verify token format (JWT should start with 'eyJ')
          if [[ ! "$TURSO_API_TOKEN" =~ ^eyJ ]]; then
            echo "⚠️  Warning: Token doesn't appear to be a valid JWT (should start with 'eyJ')"
          fi

          echo "✅ TURSO_API_TOKEN is configured"

      - name: "🔍 Verify Database Access"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          PROD_DB: ${{ vars.TURSO_PROD_DB_NAME }}
          DEV_DB: ${{ vars.TURSO_DEV_DB_NAME }}
        run: |
          echo "🔍 Verifying database access and data..."
          echo ""

          # Check production database
          echo "📊 Production Database: $PROD_DB"
          if turso db show "$PROD_DB" > /dev/null 2>&1; then
            echo "  ✅ Can access production database"

            # Try to get a row count from a table to verify data access
            ROW_COUNT=$(turso db shell "$PROD_DB" "SELECT COUNT(*) as count FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'" | tail -n 1 | tr -d ' ')
            echo "  📊 Tables in production: $ROW_COUNT"
          else
            echo "  ❌ Cannot access production database"
            exit 1
          fi

          echo ""

          # Check development database
          echo "📊 Development Database: $DEV_DB"
          if turso db show "$DEV_DB" > /dev/null 2>&1; then
            echo "  ✅ Can access development database"

            # Try to get a row count from a table to verify data access
            ROW_COUNT=$(turso db shell "$DEV_DB" "SELECT COUNT(*) as count FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'" | tail -n 1 | tr -d ' ')
            echo "  📊 Tables in development: $ROW_COUNT"
          else
            echo "  ❌ Cannot access development database"
            exit 1
          fi

          echo ""
          echo "✅ Database access verification complete"

      - name: "📸 Create Production Snapshot"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          PROD_DB: ${{ vars.TURSO_PROD_DB_NAME }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "📸 Creating Production Database Snapshot"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Generate snapshot name with YYYY-MM format
          SNAPSHOT_MONTH=$(date -u '+%Y-%m')
          SNAPSHOT_NAME="${PROD_DB}-${SNAPSHOT_MONTH}"

          echo "📊 Source Database: $PROD_DB"
          echo "📅 Snapshot Name: $SNAPSHOT_NAME"
          echo "🔍 Dry Run: ${DRY_RUN:-false}"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Check if snapshot already exists
          if turso db list | grep -q "^${SNAPSHOT_NAME}\s"; then
            echo "⚠️  Snapshot already exists: $SNAPSHOT_NAME"
            echo "   Skipping creation to avoid duplicates"
            exit 0
          fi

          if [ "${DRY_RUN}" = "true" ]; then
            echo "🔍 DRY RUN: Would create snapshot: $SNAPSHOT_NAME"
            exit 0
          fi

          # Create snapshot branch
          echo "📸 Creating snapshot branch..."
          turso db create "$SNAPSHOT_NAME" --from-db "$PROD_DB" --wait

          # Verify snapshot was created
          if turso db list | grep -q "^${SNAPSHOT_NAME}\s"; then
            echo "✅ Production snapshot created successfully"

            # Get snapshot details
            turso db show "$SNAPSHOT_NAME"
          else
            echo "❌ Failed to verify snapshot creation"
            exit 1
          fi

      - name: "📸 Create Development Snapshot"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          DEV_DB: ${{ vars.TURSO_DEV_DB_NAME }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "📸 Creating Development Database Snapshot"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Generate snapshot name with YYYY-MM format
          SNAPSHOT_MONTH=$(date -u '+%Y-%m')
          SNAPSHOT_NAME="${DEV_DB}-${SNAPSHOT_MONTH}"

          echo "📊 Source Database: $DEV_DB"
          echo "📅 Snapshot Name: $SNAPSHOT_NAME"
          echo "🔍 Dry Run: ${DRY_RUN:-false}"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Check if snapshot already exists
          if turso db list | grep -q "^${SNAPSHOT_NAME}\s"; then
            echo "⚠️  Snapshot already exists: $SNAPSHOT_NAME"
            echo "   Skipping creation to avoid duplicates"
            exit 0
          fi

          if [ "${DRY_RUN}" = "true" ]; then
            echo "🔍 DRY RUN: Would create snapshot: $SNAPSHOT_NAME"
            exit 0
          fi

          # Create snapshot branch
          echo "📸 Creating snapshot branch..."
          turso db create "$SNAPSHOT_NAME" --from-db "$DEV_DB" --wait

          # Verify snapshot was created
          if turso db list | grep -q "^${SNAPSHOT_NAME}\s"; then
            echo "✅ Development snapshot created successfully"

            # Get snapshot details
            turso db show "$SNAPSHOT_NAME"
          else
            echo "❌ Failed to verify snapshot creation"
            exit 1
          fi

      - name: "🧹 Cleanup Old Snapshots"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          PROD_DB: ${{ vars.TURSO_PROD_DB_NAME }}
          DEV_DB: ${{ vars.TURSO_DEV_DB_NAME }}
          DRY_RUN: ${{ github.event.inputs.dry_run }}
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🧹 Cleaning Up Old Snapshots (>12 months)"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # Calculate cutoff date (12 months ago)
          CUTOFF_DATE=$(date -u -d '12 months ago' '+%Y-%m' 2>/dev/null || date -u -v-12m '+%Y-%m')
          echo "📅 Cutoff Date: Snapshots before $CUTOFF_DATE will be deleted"
          echo "🔍 Dry Run: ${DRY_RUN:-false}"
          echo ""

          # List all databases
          ALL_DBS=$(turso db list | tail -n +2 | awk '{print $1}')

          DELETED_COUNT=0
          KEPT_COUNT=0

          for DB in $ALL_DBS; do
            # Check if this is a snapshot (contains YYYY-MM pattern)
            if echo "$DB" | grep -qE '-(20[0-9]{2}-[0-9]{2})$'; then
              # Extract the date from the database name
              SNAPSHOT_DATE=$(echo "$DB" | grep -oE '20[0-9]{2}-[0-9]{2}$')

              # Check if this snapshot is for our databases
              if echo "$DB" | grep -qE "^(${PROD_DB}|${DEV_DB})-"; then
                # Compare dates
                if [ "$SNAPSHOT_DATE" \< "$CUTOFF_DATE" ]; then
                  echo "🗑️  Deleting old snapshot: $DB (from $SNAPSHOT_DATE)"

                  if [ "${DRY_RUN}" != "true" ]; then
                    turso db destroy "$DB" --yes
                    echo "   ✅ Deleted"
                  else
                    echo "   🔍 DRY RUN: Would delete"
                  fi

                  DELETED_COUNT=$((DELETED_COUNT + 1))
                else
                  echo "✅ Keeping recent snapshot: $DB (from $SNAPSHOT_DATE)"
                  KEPT_COUNT=$((KEPT_COUNT + 1))
                fi
              fi
            fi
          done

          echo ""
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "📊 Cleanup Summary"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🗑️  Snapshots Deleted: $DELETED_COUNT"
          echo "✅ Snapshots Kept: $KEPT_COUNT"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

      - name: "📊 List Current Snapshots"
        env:
          TURSO_API_TOKEN: ${{ secrets.TURSO_API_TOKEN }}
          PROD_DB: ${{ vars.TURSO_PROD_DB_NAME }}
          DEV_DB: ${{ vars.TURSO_DEV_DB_NAME }}
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "📊 Current Monthly Snapshots"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

          # List all databases and filter for our snapshots
          ALL_DBS=$(turso db list | tail -n +2 | awk '{print $1}')

          echo "Production Snapshots:"
          for DB in $ALL_DBS; do
            if echo "$DB" | grep -qE "^${PROD_DB}-20[0-9]{2}-[0-9]{2}$"; then
              SNAPSHOT_DATE=$(echo "$DB" | grep -oE '20[0-9]{2}-[0-9]{2}$')
              echo "  📸 $DB (from $SNAPSHOT_DATE)"
            fi
          done

          echo ""
          echo "Development Snapshots:"
          for DB in $ALL_DBS; do
            if echo "$DB" | grep -qE "^${DEV_DB}-20[0-9]{2}-[0-9]{2}$"; then
              SNAPSHOT_DATE=$(echo "$DB" | grep -oE '20[0-9]{2}-[0-9]{2}$')
              echo "  📸 $DB (from $SNAPSHOT_DATE)"
            fi
          done

          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  notify:
    name: "📧 Notify on Failure"
    runs-on: ubuntu-latest
    needs: snapshot
    if: failure()

    steps:
      - name: "📧 Send Failure Notification"
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "❌ SNAPSHOT FAILURE NOTIFICATION"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "⏰ Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "🔗 Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "⚠️  Monthly database snapshot failed!"
          echo "   Please check the workflow logs and investigate."
          echo ""
          echo "🔍 Common Issues:"
          echo "   - Turso authentication failure (check TURSO_AUTH_TOKEN)"
          echo "   - Database name mismatch (check GitHub variables)"
          echo "   - Database quota exceeded (check Turso dashboard)"
          echo "   - Snapshot already exists (may not be an error)"
          echo ""
          echo "📚 See docs/DISASTER_RECOVERY.md for troubleshooting guidance"
